/*
** SCCSID("@(#)default.h	3.2 (SVID) 12/23/86");
*/

# define DEFAULT_OBJ_FILE	NULL;
# define DEFAULT_USE_STDIN	FALSE;

# define DEFAULT_SHOW_STRUCT	FALSE
# define DEFAULT_SHOW_VAR	FALSE

# define DEFAULT_TERM_TYPE	"SVVS3"

# define DEFAULT_USE_PIPE	FALSE
# define DEFAULT_PIPE_NAME	"pipe"

# define DEFAULT_HARD		FALSE
# define DEFAULT_MIN		0
# define DEFAULT_TIME		2

# define DEFAULT_BAUD_RATE	B4800
# define DEFAULT_BLOCK_DUMP	FALSE

# define DEFAULT_RUN_BLESS	TRUE
# define DEFAULT_RUN_MIMIC	TRUE
# define DEFAULT_RUN_UMPIRE	TRUE

# define DEFAULT_DIRECT		FALSE
# define DEFAULT_FLUSH_FLAG	"f"

# define DEFAULT_OUTPUT_BLESS	FALSE
# define DEFAULT_OUTPUT_MIMIC	FALSE
# define DEFAULT_OUTPUT_UMPIRE	TRUE

# define DEFAULT_RESPOND	FALSE

# define DEFAULT_BELL		FALSE
# define DEFAULT_NOISY		FALSE
# define DEFAULT_CORE_DUMP	FALSE

# define DEFAULT_SIZE_FILE	"/usr2/mcfong/Size/size"

# define DEFAULT_DUMP_ERROR	FALSE
