/*
** SCCSID("@(#)funct_tbl.h	3.3	(SVID)	12/23/86");
*/

/*
** INSERT is used to limit "Funct[]" to necessary functions
*/

# ifdef TIETLI
# define INSERT(a,b,c,d,e,f,g,h)  a,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
# define SPECIAL(a,b,c,d,e,f,g,h) a,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
# else
# define INSERT(a,b,c,d,e,f,g,h)  a,b,c,d,(PFI)e,(PFI)f,(PFI)g,(PFI)h,NULL,
# define SPECIAL(a,b,c,d,e,f,g,h) a,b,c,d,(PFI)e,(PFI)f,(PFI)g,(PFI)g,(PFI)h,
# endif

/*
**
*/

typedef	int	(*PFI)();

FUNCT_ENTRY	Funct[]	=	
{
SPECIAL("mvprintw",  0, 0, 1, p_mvprintw,  c_mvprintw,  Fnnnt0,  x_mvprintw)
SPECIAL("mvwprintw", 0, 0, 1, p_mvwprintw, c_mvwprintw, Fnwnnt0, x_mvwprintw)
SPECIAL("printw",    0, 0, 1, p_printw,    c_printw,    Fnt0,    x_printw)
SPECIAL("wprintw",   0, 0, 1, p_wprintw,   c_wprintw,   Fnwt0,   x_wprintw)

SPECIAL("mvscanw",   1, 1, 1, p_mvscanw,   c_mvscanw,   Fnnnt0,  x_mvscanw)
SPECIAL("mvwscanw",  1, 1, 1, p_mvwscanw,  c_mvwscanw,  Fnwnnt0, x_mvwscanw)
SPECIAL("scanw",     1, 1, 1, p_scanw,     c_scanw,     Fnt0,    x_scanw)
SPECIAL("wscanw",    1, 1, 1, p_wscanw,    c_wscanw,    Fnwt0,   x_wscanw)

INSERT("KEY_F",		0,0,1,fkeyoffset,    fkeyoffset,    Fnn,    Fnn)
INSERT("barber",	0,0,1,p_barber,	     c_barber,	    Fnc,    Fnc)
INSERT("broadcast",	1,0,1,p_printf,	     p_printf,	    Fnt0,   Fnt0)
INSERT("clrtrace",	0,0,1,NULL,	     t_clrtrace,    Fnn,    Fnn)
INSERT("expect",	0,0,1,xpk,	     xpk,	    Fn_,    Fn_)
INSERT("expect_flush",	0,0,1,xpk_flush,     xpk_flush,     Fn_,    Fn_)
INSERT("expect_mvcur",	0,0,1,xpk_mvcur,     xpk_mvcur,     Fn4n,   Fn4n)
INSERT("expect_putp",	0,0,1,xpk_putp,      xpk_putp,      Fnt,    Fnt)
INSERT("expect_vidattr",0,0,1,xpk_vidattr,   xpk_vidattr,   Fnn,    Fnn)
INSERT("fkeyseq",	0,0,1,fkeyseq,	     fkeyseq,	    Ftn,    Ftn)
INSERT("keyboard",	0,0,1,NULL,	     keyboard,	    Fnt0,   Fnt0)
INSERT("printf",	1,0,1,p_printf,	     NULL,	    Fnt0,   Fnt0)
INSERT("scanf",		1,1,1,p_printf,	     NULL,	    Fnt0,   Fnt0)
INSERT("sprintf",	0,0,1,tprintf,	     tprintf,	    FnTt0,  FnTt0)
INSERT("system",	0,0,1,p_system,	     NULL,	    Fnt,    Fnt)
INSERT("trace",		0,0,1,NULL,	     t_settrace,    Fnnt,   Fnnt)
INSERT("wbarber",	0,0,1,wbarber,	     c_wbarber,	    Fnwnnc, Fnmnnc)

INSERT("abstract",	0,0,1,vs_abstract,   NULL,	    Fnt0,   Fnt0)
INSERT("cleanup",	0,0,1,vs_cleanup,    NULL,	    Fnt0,   Fnt0)
INSERT("error",		0,0,1,vs_error,	     c_error,	    Fnt0,   Fnt0)
INSERT("warning",	0,0,1,vs_warning,    c_warning,	    Fnt0,   Fnt0)
INSERT("prep",		0,0,1,vs_prep,	     NULL,	    Fnt0,   Fnt0)
INSERT("temp_path",	0,0,1,p_temp_path,   p_temp_path,   Ft_,    Ft_)
INSERT("testing",	0,0,1,vs_testing,    NULL,	    Fnt0,   Fnt0)

INSERT("addch",		1,0,1,p_adch,	     c_adch,	    Fnc,    Fnc)
INSERT("addstr",	1,0,1,p_adstr,	     c_adstr,	    Fnt,    Fnt)
INSERT("attroff",	1,0,1,p_offattr,     c_offattr,	    Fnn,    Fnn)
INSERT("attron",	1,0,1,p_onattr,	     c_onattr,	    Fnn,    Fnn)
INSERT("attrset",	1,0,1,p_setattr,     c_setattr,	    Fnn,    Fnn)
INSERT("beep",		0,0,1,Zbeep,	     c_beep,	    Fn_,    Fn_)
INSERT("box",		0,0,1,Zbox,	     c_box,	    Fnwcc,  Fnmcc)
INSERT("cbreak",	0,0,1,Zcbreak,       NULL,          Fn_,    Fn_)
INSERT("clear",		1,0,1,p_clear,	     c_clear,	    Fn_,    Fn_)
INSERT("clearok",	0,0,1,Zclearok,	     c_clrok,	    Fnwb,   Fnmb)
INSERT("clrtobot",	1,0,1,p_clrbot,      c_clrbot,	    Fn_,    Fn_)
INSERT("clrtoeol",	1,0,1,p_clreol,      c_clreol,	    Fn_,    Fn_)
INSERT("copywin",	0,0,1,Zcopywin,	     c_copywin,	    Fnww7n, Fnmm7n)
INSERT("delay_output",	0,0,1,Zdelay_output, NULL,	    Fnn,    Fnn)
INSERT("delch",		1,0,1,p_dlch,	     c_dlch,	    Fn_,    Fn_)
INSERT("deleteln",	1,0,1,p_deleteln,    c_deleteln,    Fn_,    Fn_)
INSERT("delwin",	0,0,1,Zdelwin,	     c_delwin,	    Fnw,    Fnm)
INSERT("doupdate",	0,0,1,Zdoupdate,     c_doupdate,    Fn_,    Fn_)
INSERT("echo",		0,0,1,Zecho,	     c_echo,	    Fn_,    Fn_)
INSERT("echochar",	1,0,1,p_charecho,    c_charecho,    Fnc,    Fnc)
INSERT("endwin",	0,0,1,p_endwin,	     NULL,	    Fn_,    Fn_)
INSERT("erase",		1,0,1,p_erase,	     c_erase,	    Fn_,    Fn_)
INSERT("flash",		0,0,1,Zflash,	     c_flash,	    Fn_,    Fn_)
INSERT("flushinp",	0,0,1,Zflushinp,     c_flushinp,    Fn_,    Fn_)
INSERT("getbegyx",	1,0,1,p_getbegyx,    c_getbegyx,    Fnwnn,  Fnmnn)
INSERT("getch",		1,1,1,p_gtch,	     c_gtch,	    Fn_,    Fn_)
INSERT("getmaxyx",	1,0,1,p_getmaxyx,    c_getmaxyx,    Fnwnn,  Fnmnn)
INSERT("getstr",	1,1,1,p_gtstr,	     c_gtstr,	    FnT,    FnT)
INSERT("getyx",		1,0,1,p_getyx,	     c_getyx,	    Fnwnn,  Fnmnn)
INSERT("idlok",		0,0,1,Zidlok,	     NULL,	    Fnwb,   Fnmb)
INSERT("inch",		1,0,1,p_inc,	     c_inc,	    Fc_,    Fc_)
INSERT("initscr",	1,0,0,p_initscr,     cx_initscr,    Fn_,    Fn_)
INSERT("insch",		1,0,1,p_insch,	     c_insch,	    Fnc,    Fnc)
INSERT("insertln",	1,0,1,p_insertln,    c_insertln,    Fn_,    Fn_)
INSERT("keypad",	0,0,1,Zkeypad,	     c_keypad,	    Fnwb,   Fnmb)
INSERT("leaveok",	0,0,1,Zleaveok,	     c_leaveok,	    Fnwb,   Fnmb)
INSERT("move",		1,0,1,p_move,	     c_move,	    Fnnn,   Fnnn)
INSERT("mvaddch",	1,0,1,p_addchmv,     c_addchmv,	    Fnnnc,  Fnnnc)
INSERT("mvaddstr",	1,0,1,p_addstrmv,    c_addstrmv,    Fnnnt,  Fnnnt)
INSERT("mvcur",		0,0,1,Zmvcur,	     c_mvcur,	    Fn4n,   Fn4n)
INSERT("mvdelch",	1,0,1,p_delchmv,     c_delchmv,	    Fnnn,   Fnnn)
INSERT("mvgetch",	1,1,1,p_getchmv,     c_getchmv,	    Fnnn,   Fnnn)
INSERT("mvgetstr",	1,1,1,p_getstrmv,    c_getstrmv,    FnnnT,  FnnnT)
INSERT("mvinch",	1,0,1,p_inchmv,	     c_inchmv,	    Fcnn,   Fcnn)
INSERT("mvinsch",	1,0,1,p_mvinsch,     c_mvinsch,	    Fnnnc,  Fnnnc)
INSERT("mvwaddch",	1,0,1,p_chaddmvw,    c_chaddmvw,    Fnwnnc, Fnmnnc)
INSERT("mvwaddstr",	1,0,1,p_straddmvw,   c_straddmvw,   Fnw2nt, Fnmnnt)
INSERT("mvwdelch",	1,0,1,p_chdelmvw,    c_chdelmvw,    Fnwnn,  Fnmnn)
INSERT("mvwgetch",	1,1,1,p_chgetmvw,    c_chgetmvw,    Fnwnn,  Fnmnn)
INSERT("mvwgetstr",	1,1,1,p_strgetmvw,   c_strgetmvw,   FnwnnT, FnmnnT)
INSERT("mvwin",		0,0,1,Zmvwin,	     c_winmv,	    Fnwnn,  Fnmnn)
INSERT("mvwinch",	1,0,1,p_chinmvw,     c_chinmvw,	    Fcwnn,  Fcmnn)
INSERT("mvwinsch",	1,0,1,p_mvwinsch,    c_mvwinsch,    Fnwnnc, Fnmnnc)
INSERT("newpad",	0,0,1,Znewpad,	     c_newpad,	    Fwnn,   Fmnn)
INSERT("newwin",	0,0,1,Znewwin,	     c_newwin,	    Fwnnnn, Fmnnnn)
INSERT("noecho",	0,0,1,Znoecho,	     c_noecho,	    Fn_,    Fn_)
INSERT("overlay",	0,0,1,Zoverlay,	     c_ovrlay,	    Fnww,   Fnmm)
INSERT("overwrite",	0,0,1,Zoverwrite,    c_ovrwrite,    Fnww,   Fnmm)
INSERT("pechochar",	0,0,1,Zpechochar,    c_pechochar,   Fnwc,   Fnmc)
INSERT("pnoutrefresh",	0,0,1,Zpnoutrefresh, c_pnoutrefresh,Fnw6n,  Fnm6n)
INSERT("prefresh",	0,0,1,Zprefresh,     c_prefresh,    Fnw6n,  Fnm6n)
INSERT("putp",		0,0,1,Zputp,	     NULL,	    Fnt,    Fnt)
INSERT("refresh",	1,0,0,p_refresh,     c_refresh,	    Fn_,    Fn_)
INSERT("scr_dump",	0,0,1,p_scrdump,     c_scrdump,     Fnt,    Fnt)
INSERT("scr_init",	0,0,1,Zscr_init,     c_scrinit,	    Fnt,    Fnt)
INSERT("scr_restore",	0,0,1,Zscr_restore,  c_scrrestore,  Fnt,    Fnt)
INSERT("scroll",	0,0,1,Zscroll,	     c_scroll,	    Fnw,    Fnm)
INSERT("scrollok",	0,0,1,Zscrollok,     c_okscroll,    Fnwb,   Fnmb)
INSERT("setscrreg",	1,0,1,p_setscrreg,   NULL,	    Fnnn,   Fnnn)
INSERT("slk_clear",	0,0,1,Zslk_clear,    c_slkclear,    Fn_,    Fn_)
INSERT("slk_init",	0,0,1,Zslk_init,     c_slkinit,	    Fnn,    Fnn)
INSERT("slk_label",	0,0,1,Zslk_label,    c_slklabel,    Ftn,    Ftn)
INSERT("slk_noutrefresh",0,0,1,Zslk_noutrefresh,c_slknoutrefresh,Fn_,Fn_)
INSERT("slk_refresh",	0,0,1,Zslk_refresh,  c_slk_refresh, Fn_,    Fn_)
INSERT("slk_restore",	0,0,1,Zslk_restore,  c_slkrestore,  Fn_,    Fn_)
INSERT("slk_set",	0,0,1,Zslk_set,	     c_slkset,	    Fnntn,  Fnntn)
INSERT("slk_touch",	0,0,1,Zslk_touch,    c_slktouch,    Fn_,    Fn_)
INSERT("standend",	1,0,1,p_endstand,    c_endstand,    Fn_,    Fn_)
INSERT("standout",	1,0,1,p_standout,    c_standout,    Fn_,    Fn_)
INSERT("subpad",	0,0,1,Zsubpad,	     c_subpad,	    Fwwnnnn,Fmmnnnn)
INSERT("subwin",	0,0,1,Zsubwin,	     c_subwin,	    Fwwnnnn,Fmmnnnn)
INSERT("tgetnum",	0,0,1,Ztgetnum,	     NULL,	    Fnt,    Fnt)
INSERT("touchline",	0,0,1,Ztouchline,    c_linetouch,   Fnwnn,  Fnmnn)
INSERT("touchwin",	0,0,1,Ztouchwin,     c_wintouch,    Fnw,    Fnm)
INSERT("unctrl",	1,0,1,p_unctrl,	     c_unctrl,	    Ftc,    Ftc)
INSERT("ungetch",	0,0,1,Zungetch,	     c_ungetch,	    Fnc,    Fnc)
INSERT("vidattr",	0,0,1,Zvidattr,	     NULL,	    Fnn,    Fnn)
INSERT("waddch",	0,0,1,Zwaddch,	     c_wchadd,	    Fnwc,   Fnmc)
INSERT("waddstr",	0,0,1,Zwaddstr,	     c_wstradd,	    Fnwt,   Fnmt)
INSERT("wattroff",	0,0,1,Zwattroff,     c_woffattr,    Fnwn,   Fnmn)
INSERT("wattron",	0,0,1,Zwattron,	     c_wonattr,	    Fnwn,   Fnmn)
INSERT("wattrset",	0,0,1,Zwattrset,     c_wsetattr,    Fnwn,   Fnmn)
INSERT("wclear",	0,0,1,Zwclear,	     c_wclear,	    Fnw,    Fnm)
INSERT("wclrtobot",	0,0,1,Zwclrtobot,    c_wbotclr,	    Fnw,    Fnm)
INSERT("wclrtoeol",	0,0,1,Zwclrtoeol,    c_weolclr,	    Fnw,    Fnm)
INSERT("wdelch",	0,0,1,Zwdelch,	     c_wchdel,	    Fnw,    Fnm)
INSERT("wdeleteln",	0,0,1,Zwdeleteln,    c_wdeleteln,   Fnw,    Fnm)
INSERT("wechochar",	0,0,1,Zwechochar,    c_wechochar,   Fnwc,   Fnmc)
INSERT("werase",	0,0,1,Zwerase,	     c_werase,	    Fnw,    Fnm)
INSERT("wgetch",	0,1,1,Zwgetch,	     c_wchget,	    Fnw,    Fnm)
INSERT("wgetstr",	1,1,1,p_wgetstr,     c_wgetstr,	    FnwT,   FnmT)
INSERT("winch",		1,0,1,p_wchin,	     c_wchin,	    Fcw,    Fcm)
INSERT("winsch",	0,0,1,Zwinsch,	     c_winsch,	    Fnwc,   Fnmc)
INSERT("winsertln",	0,0,1,Zwinsertln,    c_wlninsert,   Fnw,    Fnm)
INSERT("wmove",		0,0,1,Zwmove,	     c_wmove,	    Fnwnn,  Fnmnn)
INSERT("wnoutrefresh",	0,0,1,Zwnoutrefresh, c_wnoutrefresh,Fnw,    Fnm)
INSERT("wrefresh",	0,0,0,Zwrefresh,     c_wrefresh,    Fnw,    Fnm)
INSERT("wsetscrreg",	1,0,1,p_wsetscrreg,  NULL,	    Fnwnn,  Fnmnn)
INSERT("wstandend",	0,0,1,Zwstandend,    c_wendstand,   Fnw,    Fnm)
INSERT("wstandout",	0,0,1,Zwstandout,    c_wstandout,   Fnw,    Fnm)

0
}
;
