/*
 *	sv_base.h - macro definitions for BA_OS and BA_LIB function replacement
 */

#ifdef	UNDEF
ident	"@(#)sv_base.h	1.7"
#endif

#define compile			Zcompile
#define step			Zstep
#define advance			Zadvance
#define	abort			Zabort
#define	access			Zaccess
#define	alarm			Zalarm
#define	chdir			Zchdir
#define	chmod			Zchmod
#define	chown			Zchown
#define	close			Zclose
#define	closedir		Zclosedir
#define	creat			Zcreat
#define	dup			Zdup
#define	dup2			Zdup2
#define	execl			Zexecl
#define	execv			Zexecv
#define	execle			Zexecle
#define	execve			Zexecve
#define	execlp			Zexeclp
#define	execvp			Zexecvp
#define	exit			Zexit
#define	_exit			Z_exit
#define	fclose			Zfclose
#define	fflush			Zfflush
#define	fcntl			Zfcntl
#define	fopen			Zfopen
#define	freopen			Zfreopen
#define	fdopen			Zfdopen
#define	fork			Zfork
#define	fread			Zfread
#define	fwrite			Zfwrite
#define	fseek			Zfseek
#define	rewind			Zrewind
#define	ftell			Zftell
#define	getcwd			Zgetcwd
#define	getpid			Zgetpid
#define	getpgrp			Zgetpgrp
#define	getppid			Zgetppid
#define	getuid			Zgetuid
#define	geteuid			Zgeteuid
#define	getgid			Zgetgid
#define	getegid			Zgetegid
#define	ioctl			Zioctl
#define	kill			Zkill
#define	link			Zlink
#define	lockf			Zlockf
#define	lseek			Zlseek
#define	malloc			Zmalloc
#define	free			Zfree
#define	realloc			Zrealloc
#define	calloc			Zcalloc
#define	mallopt			Zmallopt
#define	mkdir			Zmkdir
#define	mknod			Zmknod
#define	mount			Zmount
#define	open			Zopen
#define	opendir			Zopendir
#define	pause			Zpause
#define	pipe			Zpipe
#define	popen			Zpopen
#define	pclose			Zpclose
#define	read			Zread
#define	readdir			Zreaddir
#define	rmdir			Zrmdir
#define	setpgrp			Zsetpgrp
#define	setuid			Zsetuid
#define	setgid			Zsetgid
#define	signal			Zsignal
#define	sleep			Zsleep
#define	stat			Zstat
#define	fstat			Zfstat
#define	stime			Zstime
#define	strdup			Zstrdup
#define	sync			Zsync
#define	system			Zsystem
#define	time			Ztime
#define	times			Ztimes
#define	ulimit			Zulimit
#define	umask			Zumask
#define	umount			Zumount
#define	uname			Zuname
#define	unlink			Zunlink
#define	ustat			Zustat
#define	utime			Zutime
#define	wait			Zwait
#define	write 			Zwrite 

#define	abs				Zabs
#define	j0				Zj0
#define	j1				Zj1
#define	jn				Zjn
#define	y0				Zy0
#define	y1				Zy1
#define	yn				Zyn
#define	bsearch			Zbsearch
#define	clock			Zclock
#define	toupper			Ztoupper
#define	tolower			Ztolower
#define	crypt			Zcrypt
#define	setkey			Zsetkey
#define	encrypt			Zencrypt
#define	ctermid			Zctermid
#define	ctime			Zctime
#define	localtime		Zlocaltime
#define	gmtime			Zgmtime
#define	asctime			Zasctime
#define	tzset			Ztzset
#define	drand48			Zdrand48
#define	erand48			Zerand48
#define	lrand48			Zlrand48
#define	nrand48			Znrand48
#define	mrand48			Zmrand48
#define	jrand48			Zjrand48
#define	seed48			Zseed48
#define	lcong48			Zlcong48
#define	erf				Zerf
#define	erfc			Zerfc
#define	exp				Zexp
#define	log				Zlog
#define	log10			Zlog10
#define	pow				Zpow
#define	sqrt			Zsqrt
#define	floor			Zfloor
#define	ceil			Zceil
#define	fmod			Zfmod
#define	fabs			Zfabs
#define	frexp			Zfrexp
#define	ldexp			Zldexp
#define	modf			Zmodf
#define	ftw				Zftw
#define	gamma			Zgamma
#define	fgetc			Zfgetc
#define	getw			Zgetw
#define	getenv			Zgetenv
#define	getopt			Zgetopt
#define	gets			Zgets
#define	fgets			Zfgets
#define	hsearch			Zhsearch
#define	hcreate			Zhcreate
#define	hdestroy		Zhdestroy
#define	hypot			Zhypot
#define	lsearch			Zlsearch
#define	lfind			Zlfind
#define	memccpy			Zmemccpy
#define	memchr			Zmemchr
#define	memcmp			Zmemcmp
#define	memcpy			Zmemcpy
#define	memset			Zmemset
#define	mktemp			Zmktemp
#define	perror			Zperror
#define	fputc			Zfputc
#define	putw			Zputw
#define	putenv			Zputenv
#define	puts			Zputs
#define	fputs			Zfputs
#define	qsort			Zqsort
#define	rand			Zrand
#define	srand			Zsrand
#define	srand48			Zsrand48
#define	setbuf			Zsetbuf
#define	setvbuf			Zsetvbuf
#define	sinh			Zsinh
#define	cosh			Zcosh
#define	tanh			Ztanh
#define	ssignal			Zssignal
#define	sighold			Zsighold
#define	sigignore		Zsigignore
#define	sigrelse		Zsigrelse
#define	sigset			Zsigset
#define	gsignal			Zgsignal
#define	strcat			Zstrcat
#define	strncat			Zstrncat
#define	strcmp			Zstrcmp
#define	strncmp			Zstrncmp
#define	strcpy			Zstrcpy
#define	strncpy			Zstrncpy
#define	strlen			Zstrlen
#define	strchr			Zstrchr
#define	strrchr			Zstrrchr
#define	strpbrk			Zstrpbrk
#define	strspn			Zstrspn
#define	strcspn			Zstrcspn
#define	strtok			Zstrtok
#define	strtod			Zstrtod
#define	atof			Zatof
#define	strtol			Zstrtol
#define	atol			Zatol
#define	atoi			Zatoi
#define	swab			Zswab
#define	tmpfile			Ztmpfile
#define	tmpnam			Ztmpnam
#define	tempnam			Ztempnam
#define	sin				Zsin
#define	cos				Zcos
#define	tan				Ztan
#define	asin			Zasin
#define	acos			Zacos
#define	atan			Zatan
#define	atan2			Zatan2
#define	tsearch			Ztsearch
#define	tfind			Ztfind
#define	tdelete			Ztdelete
#define	twalk			Ztwalk
#define	ttyname			Zttyname
#define	isatty			Zisatty
#define	ungetc			Zungetc
#define	vprintf			Zvprintf
#define	vfprintf		Zvfprintf
#define	vsprintf		Zvsprintf  

#define	acct			Zacct
#define	chroot			Zchroot
#define	msgctl			Zmsgctl
#define	msgget			Zmsgget
#define	msgsnd			Zmsgsnd
#define	msgrcv			Zmsgrcv
#define	nice			Znice
#define	plock			Zplock
#define	profil			Zprofil
#define	ptrace			Zptrace
#define	semctl			Zsemctl
#define	semget			Zsemget
#define	semop			Zsemop
#define	shmctl			Zshmctl
#define	shmget			Zshmget
#define	shmat			Zshmat
#define	shmdt			Zshmdt
